#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi

if [[ $XDG_VTNR ]]; then
  if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
  fi
else
  echo "# Insert cool SSH welcome here #"
fi
