#!/bin/bash

#DEFAULT COLORS
DEFAULT_COLOR="#40ff40"
WARNING_COLOR="#bbff00"
CRITICAL_COLOR="#ff7700"
FULL_COLOR"#ff0055"

[[ $1 = "" ]] && LOCATION="/" || LOCATION=$1

#$TEXT_OUT=>text to print || $TEXT_COLOR => display color
function PrintText {
  echo $TEXT_OUT
  echo $TEXT_OUT
  echo $TEXT_COLOR
}

#Click actions
case "$BLOCK_BUTTON" in
    1) #Left Click - File manager
      if [[ $LOCATION = "/" ]]; then
        pcmanfm /home/$USER/ &
      else
        pcmanfm $LOCATION &
      fi;;
esac

#Get data
FREE_SPACE=$(df -h -P $LOCATION | awk '/\/.*/ {print $4}')
USAGE_PERCENT=$(df -h -P $LOCATION | awk '/\/.*/ {print $5}' | cut -d% -f1)
#Set output color
TEXT_COLOR=""
case $USAGE_PERCENT in
  [0-75]*) TEXT_COLOR=$DEFAULT_COLOR;;
  [76-85]*) TEXT_COLOR=$WARNING_COLOR;;
  [86-95]*) TEXT_COLOR=$CRITICAL_COLOR;;
  [96-100]*) TEXT_COLOR=$FULL_COLOR;;
esac

#Set output
if [[ $2 = "--name" ]]; then
  if [[ $LOCATION = "/" ]]; then
    TEXT_OUT="sys: $FREE_SPACE"
  else
    TEXT_OUT="$(echo "$LOCATION" | cut -c2-): $FREE_SPACE"
  fi
else
  TEXT_OUT=$FREE_SPACE
fi
#Display info
PrintText
