#!/bin/sh
USER=""
PASS=""

DEFAULT_COLOR="#40ff40"
EMAIL_LOW_COLOR="#bbff00"
EMAIL_MID_COLOR="#ff7700"
EMAIL_HIGH_COLOR="#ff0055"

DEFAULT=""
UNREAD=""

function PrintText {
  echo $TEXT_OUT
  echo $TEXT_OUT
  echo $TEXT_COLOR
}

COUNT=`curl -su $USER:$PASS https://mail.google.com/mail/feed/atom || echo "<fullcount>unknown number of</fullcount>"`
COUNT=`echo "$COUNT" | grep -oPm1 "(?<=<fullcount>)[^<]+" `

case "$BLOCK_BUTTON" in
    1)  xdg-open https://mail.google.com/ &;; #Left Click - Open gmail in default browser
esac

if [ "$COUNT" = "0" ]; then
  TEXT_OUT=$DEFAULT
  TEXT_COLOR=$DEFAULT_COLOR
elif [[ "$COUNT" < "2" ]]; then
  TEXT_OUT="$UNREAD"
  TEXT_COLOR=$EMAIL_LOW_COLOR
elif [[ "$COUNT" < "5" ]]; then
  TEXT_OUT="$UNREAD $COUNT"
  TEXT_COLOR=$EMAIL_MID_COLOR
else
  TEXT_OUT="$UNREAD $COUNT"
  TEXT_COLOR=$EMAIL_HIGH_COLOR
fi

case "$BLOCK_BUTTON" in
    1)  xdg-open https://mail.google.com/ &;; #Left Click - Open gmail in default browser
esac


PrintText
