#!/bin/bash

#DEFAULT COLORS
UPTODATE_COLOR="#40ff40"
REGULAR_UPDATE_COLOR="#bbff00"
IMPORTANT_UPDATE_COLOR="#ff7700"
SYSTEM_UPDATE_COLOR="#ff0055"

#LOCAL
NeedUpdate="true"
! [[ $(pacman -Qu | awk '!/\[*\]/ {print}') = "" ]] && NeedUpdate="true" || NeedUpdate="false" #Created exception for ignored packages

#$TEXT_OUT=>text to print || $TEXT_COLOR => display color
function PrintText {
  echo $TEXT_OUT
  echo $TEXT_OUT
  echo $TEXT_COLOR
}

if [[ $NeedUpdate = "true" ]]; then
  #Regular system updates
  TEXT_COLOR=$REGULAR_UPDATE_COLOR
  TEXT_OUT="Optional system updates available"
  #Watched updates (@Important)
  if [ "$#" -ne 0 ]; then
    for _watched in "$@";  do
      if ! [[ $(pacman -Qu | grep $_watched) = "" ]]; then
        TEXT_COLOR=$IMPORTANT_UPDATE_COLOR
        TEXT_OUT="Important system updates available"
      fi
    done
  fi
  #System updates
  if ! [[ $(pacman -Qu | grep linux) = "" ]]; then
    TEXT_COLOR=$SYSTEM_UPDATE_COLOR
    TEXT_OUT="Critical system updates available"
  fi
else
  TEXT_COLOR=$UPTODATE_COLOR
  TEXT_OUT="All packages are up to date"
fi
#Display info
PrintText
