#!/bin/sh

#Locals
Source_Path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
INSTALL_i3=$Source_Path"install"
INSTALL_DEV=$Source_Path"dev_install"
FDE_Path=$Source_Path"../FDE/"
KERNEL=$FDE_Path"Kernel.sh"
GRAPHICS=$FDE_Path"Graphics.sh"
USER=$FDE_Path"User.sh"

sh ""$FDE_Path"Functions.sh" MakePKG_Patch

#Main loop
while [ "$INPUT_OPTION" != "end" ]; do
  #clear
  echo "Please type the number of selected task! (Press \"ESC\" to quit.)"
  echo "1. Kernel"
  echo "2. Graphics"
  echo "3. User"
  echo "4. Install i3WM with custom settings"
  echo "5. Install developer packages"
  read -sn1 INPUT_OPTION
  case $INPUT_OPTION in
    '1') sh $KERNEL;;# clear;; #sh $KERNEL
    '2') sh $GRAPHICS; clear;;
    '3') sh $USER; clear;;
    '4') sh $INSTALL_i3; clear;;
    '5') sh $INSTALL_DEV; clear;;
    $'\e') clear; break;;
  esac
done

#Revert changes to makepkg
cp ""$FDE_Path"patches/makepkg_BU" /usr/bin/makepkg
