#!/bin/sh
clear;
#Local globals-------------------------------------------------------------------------------------------------------------------------------------------------------
Source_Path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../";
DEFAULT_USER="wisp"; #Edit this to your username
FANCY_ROOT="false"; #Change this if you dont need anything for root
ALL_USER="false"; #Change this if you want to install everything for all user
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#----------------------------------------------------Install default packages to create environment----------------------------------------------------
#Install i3WM and dependencies------------------------------------------------------------------------------------------------------------------------------
pacman -S --noconfirm pulseaudio pulseaudio-alsa alsa-utils; #Audio
pacman -S --noconfirm xorg xorg-xinit; #Window system
pacman -S --noconfirm i3; #Window manager
#Environment settings-------------------------------------------------------------------------------------------------------------------------------------------
timedatectl set-timezone Europe/Budapest; #Timezone
localectl --no-convert set-x11-keymap hu; #Set keyboard layout
pacman -S --noconfirm feh; #Background handler
pacman -S --noconfirm dmenu; #Application launcher
pacman -S --noconfirm cron; systemctl enable cronie.service; #Time based task scheduler
#----------------------------------------------------------------------i3 Settings------------------------------------------------------------------------------------
# $1 = $HOME folder---------------------------------------------------------------------------------------------------------------------------------------------
function CopyConfigs {
  echo "exec i3" > "$1".xinitrc
  mkdir -p "$1".config/i3/
  echo "" > "$1".config/i3/config; cp ""$Source_Path"i3/config" "$1".config/i3/config; #i3 config
  cp ""$Source_Path"i3/i3blocks" "$1".i3blocks.conf; #i3blocks config
  cp -r ""$Source_Path"i3/blocklets" "$1".blocklets; #i3 blocklets
  echo "" > "$1".config/i3/Xresources; cp ""$Source_Path"i3/Xresources" "$1".config/i3/Xresources; #Xorg display settings
  echo "" > "$1".fehbg; cp ""$Source_Path"i3/background" "$1".fehbg; #Set background script
  if ! [[ $username = "" ]]; then
    chown -R $username "$1"
  else
    chown -R $DEFAULT_USER "$1"
  fi
}
#Defaults-------------------------------------------------------------------------------------------------------------------------------------------------------------
cp ""$Source_Path"Personal/00-driver.conf" /etc/X11/xorg.conf.d/00-driver.conf; #Xorg driver settings
cp ""$Source_Path"i3/default_wallpaper.png" /default_wallpaper.png; #Copy a default wallpaper
crontab ""$Source_Path"i3/root_cron"; #Cron tasks for root
#Split copy stuff by user settings-----------------------------------------------------------------------------------------------------------------------------
if [[ $ALL_USER = "true" ]]; then
  if [[ $FANCY_ROOT = "true" ]]; then
    sed -n '/\/bin\/bash/p' /etc/passwd | cut -d: -f1 | while read -r username; do
      if [[ $username = "root" ]]; then
        CopyConfigs "/root/"
      else
        CopyConfigs "/home/$username/"
      fi
    done
  else
    sed -n '/\/bin\/bash/p' /etc/passwd | cut -d: -f1 | while read -r username; do
      if ! [[ $username = "root" ]]; then
        CopyConfigs "/home/$username/"
      fi
    done
  fi
else
  if [[ $FANCY_ROOT = "true" ]]; then
    CopyConfigs "/root/"
    CopyConfigs "/home/$DEFAULT_USER/"
  else
    CopyConfigs "/home/$DEFAULT_USER/"
  fi
fi
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Fonts-----------------------------------------------------------------------------------------------------------------------------------------------------------------
pacman -S --noconfirm ttf-dejavu ttf-inconsolata ttf-font-awesome; #To look atleast decent
sh ""$Source_Path"FDE/Functions.sh" InstallFromAUR "ttf-font-logos"; #Needed for Arch linux logo
#Default apps-------------------------------------------------------------------------------------------------------------------------------------------------------
pacman -S --noconfirm neofetch; #PC information
pacman -S --noconfirm htop; #Process manager
pacman -S --noconfirm rxvt-unicode urxvt-perls; #Terminal
pacman -S --noconfirm pavucontrol; #PulseAudio Volume controller
pacman -S --noconfirm scrot xclip; #Print screen tool/Copy to clipboard
pacman -S --noconfirm pcmanfm; #File manager
pacman -S --noconfirm file-roller; #Archive manager
pacman -S --noconfirm chromium; #Browser
pacman -S --noconfirm atom; #Text editor
sh ""$Source_Path"FDE/Functions.sh" InstallFromAUR "cpplint"; #Needed for atom cpp-linter plugin
pacman -S --noconfirm transmission-qt; #Torrent
pacman -S --noconfirm vlc; #Video player
pacman -S --noconfirm viewnior; #Image viewer
#Terminal/Shell extensions--------------------------------------------------------------------------------------------------------------------------------------
pacman -S --noconfirm bc; #Shell extension - Floating point division
sh ""$Source_Path"FDE/Functions.sh" InstallFromAUR "urxvt-resize-font-git"; #Terminal extension (Resize font on fly)
pacman -S --noconfirm awesome-terminal-fonts; #Awesome fonts for terminal use
sh ""$Source_Path"FDE/Functions.sh" InstallFromAUR "aurman"; #AUR package installer
#Atom extensions----------------------------------------------------------------------------------------------------------------------------------------------------------
apm install linter; # Atom linter
apm install linter-ui-default; # Linter Atom-UI
apm install linter-cpplint; # Atom C++ linter
apm install clang-format; # Reformat C/C++ code
apm install language-cmake; # Atom CMake language
apm install autocomplete-cmake; # Atom CMake autocomplete
apm install intentions busy-signal; # Atom random stuff
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
