#!/bin/bash

#DEFAULT COLORS
DEFAULT_COLOR="#40ff40"
WARNING_COLOR="#bbff00"
CRITICAL_COLOR="#ff7700"
FULL_COLOR"#ff0055"
HOME_SYMBOL=""
DRIVE_SYMBOL=""

[[ $1 = "" ]] && LOCATION="/" || LOCATION=$1

#$TEXT_OUT=>text to print || $TEXT_COLOR => display color
function PrintText {
  echo $TEXT_OUT
  echo $TEXT_OUT
  echo $TEXT_COLOR
}

if [[ $LOCATION = "/" ]]; then
  if [[ $EUID -ne 0 ]]; then
    LOCATION="/home/$USER/"
  else
    LOCATION="/root/"
  fi
fi

#Click actions
case "$BLOCK_BUTTON" in
    1) pcmanfm $LOCATION &;;
esac

#Get data
FREE_SPACE=$(df -h -P $LOCATION | awk '/\/.*/ {print $4}')
USAGE_PERCENT=$(df -h -P $LOCATION | awk '/\/.*/ {print $5}' | cut -d% -f1)
#Set output color
TEXT_COLOR=""
if [[ $USAGE_PERCENT -le 75 ]]; then
  TEXT_COLOR=$DEFAULT_COLOR
elif [[ $USAGE_PERCENT -le 85  ]]; then
  TEXT_COLOR=$WARNING_COLOR
elif [[ $USAGE_PERCENT -le 96 ]]; then
  TEXT_COLOR=$CRITICAL_COLOR
else
  TEXT_COLOR=$FULL_COLOR
fi

#Set output
if [[ $2 = "--name" ]]; then
  if [[ $LOCATION = "/" ]]; then
    TEXT_OUT="sys: $FREE_SPACE"
  else
    TEXT_OUT="$(echo "$LOCATION" | cut -c2-): $FREE_SPACE"
  fi
else
  if [[ $LOCATION = "/home/"* ]] || [[ $LOCATION = "/root/" ]]; then
    TEXT_OUT="$HOME_SYMBOL $FREE_SPACE"
  else
    TEXT_OUT="$DRIVE_SYMBOL $FREE_SPACE"
  fi

fi

#Display info
PrintText
